### ISSUE TITLE
xterm fails to start on AWS and docker-compose

### ISSUE THREAD

**Issue by roncewind** [Senzing/docker-xterm#127]
The follow error was found in AWS and recreated with docker-compose

```
22-08-26 21:57:01,196 senzing-50240102I Senzing X-term serving on http://0.0.0.0:5000/
2022-08-26 21:57:01,196 WebSocket transport not available. Install simple-websocket for improved performance.
Traceback (most recent call last):
  File "/app/xterm.py", line 19, in <module>
    sys.exit(main())
  File "/app/app.py", line 333, in main
    SOCKETIO.run(APP, debug=args.debug, port=args.port, host=args.host)
  File "/usr/local/lib/python3.9/dist-packages/flask_socketio/__init__.py", line 639, in run
    raise RuntimeError('The Werkzeug web server is not '
RuntimeError: The Werkzeug web server is not designed to run in production. Pass allow_unsafe_werkzeug=True to the run() method to disable this error.
```

It may have been introduced with the update to Flask 5.3.0:  https://github.com/Senzing/docker-xterm/blob/28f5eb640f5ee4c892c8f8502c3bc2162d5bdacd/requirements.txt

**Comment by docktermj** [comment]
In `requirements.txt`, I verified that the following works:

```
Flask-SocketIO==5.2.0
```

and this creates the issue:

```
Flask-SocketIO==5.3.0
```

Will make code changes for version Flask-SockerIO 5.3.0.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/docker-xterm/pull/128
