### ISSUE TITLE
xterm hangs when using G2Explorer.py

### ISSUE THREAD

**Issue by roncewind** [Senzing/docker-xterm#68]
I deployed a new Marketplace stack and tried testing G2Explorer. 

`(g2) help` works.
`(g2) search john smith` returned 4 results, just like the web app.
`(g2) compare 1200006, 2000001` works
`(g2) get 1` (or any number) hangs.  with this error message in the logs:

```
2022-05-13 20:04:48,378 senzing-50240101I Senzing X-term version: 1.2.0 updated: 2021-08-30
--
2022-05-13 20:04:48,378 senzing-50240102I Senzing X-term serving on http://0.0.0.0:5000
2022-05-13 20:05:32,311 senzing-50240103I Connected. PID: None
2022-05-13 20:05:32,314 senzing-50240104I Started background task. PID: 8 Running command: 'bash'
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/app/app.py", line 131, in read_os_write_socketio
output = os.read(app.config["file_descriptor"], max_read_bytes).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4094: unexpected end of data
```

work around, kill the running xterm task and let another respawn and don't use `get`.  
`get <any number>` will hang any xterm task.

Note this works in the SSHD container which is why I believe it's an Xterm issue.

**Comment by roncewind** [comment]
Retested this with basic CFT, most recent marketplace CFT, and the marketplace CFT in S3 and I could not reproduce this error.  very odd.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/docker-xterm/pull/74

**Comment by roncewind** [comment]
Closing for now.

**Comment by roncewind** [comment]
xterm is behaving badly again.
```
2022-06-09 19:37:22,170 senzing-50240101I Senzing X-term version: 1.3.0 updated: 2022-05-19
2022-06-09 19:37:22,170 senzing-50240102I Senzing X-term serving on http://0.0.0.0:5000/
2022-06-09 19:41:05,687 senzing-50240103I Connected. PID: None
2022-06-09 19:41:05,690 senzing-50240104I Started background task. PID: 8 Running command: 'bash'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app.py", line 153, in read_os_write_socketio
    output = os.read(APP.config["file_descriptor"], max_read_bytes).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4094: unexpected end of data
2022-06-09 19:44:38,132 senzing-50240103I Connected. PID: 8
beyond the error, it’s odd that it says it’s version 1.3.0 when the cloudformation is using Xterm:public.ecr.aws/senzing/xterm:1.3.1
[12:51](https://senzing.slack.com/archives/D0240TDD6E5/p1654804303415699)
```
when it got here i was running G2Explorer.py get 13 which is an id of a record.  it hung in xterm, but ran fine in sshd.  i closed the xterm tab and opened a new one, the prompt doesn’t come back… as if it’s still hung.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/docker-xterm/pull/74
- https://github.com/Senzing/docker-xterm/pull/78
- https://github.com/Senzing/docker-xterm/pull/79
- https://github.com/Senzing/docker-xterm/pull/80
- https://github.com/Senzing/docker-xterm/pull/81
