### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-xterm#94]
Current issue:

```console
Traceback (most recent call last):
  File "/app/xterm.py", line 15, in <module>
    from app import main
  File "/app/app.py", line 24, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
```

**Comment by docktermj** [comment]
Pull Requests:

- https://github.com/Senzing/docker-xterm/pull/95
